Repository BidNamu/bidnamu-backend, pull requests merged in 2023-12, with the labels that each got.

#32 [#28] AWS 설정 불러오는 방법 변경
  src/main/java/com/bidnamu/bidnamubackend/global/config/S3Config.java
Labels: refactor

#33 [#28] 파일 업로드 관련 기능 추가
  src/main/java/com/bidnamu/bidnamubackend/file/config/S3Config.java
  src/main/java/com/bidnamu/bidnamubackend/file/exception/FileUploadException.java
  src/main/java/com/bidnamu/bidnamubackend/file/service/FileService.java
  src/main/java/com/bidnamu/bidnamubackend/file/service/S3FileService.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/bidnamu/bidnamubackend/global/service/FileService.java
  src/test/java/com/bidnamu/bidnamubackend/file/service/S3FileServiceTest.java
Labels: feature

#29 [#7] 로그인 기능 구현
  build.gradle
  src/main/java/com/bidnamu/bidnamubackend/auth/config/JwtAccessDeniedHandler.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/JwtProperties.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/SecurityConfig.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/TokenAuthenticationFilter.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/TokenProvider.java
  src/main/java/com/bidnamu/bidnamubackend/auth/controller/AuthController.java
  src/main/java/com/bidnamu/bidnamubackend/auth/domain/Authority.java
  src/main/java/com/bidnamu/bidnamubackend/auth/dto/request/LoginRequestDto.java
  src/main/java/com/bidnamu/bidnamubackend/auth/dto/request/RefreshTokenRequestDto.java
  src/main/java/com/bidnamu/bidnamubackend/auth/dto/response/LoginResponseDto.java
  src/main/java/com/bidnamu/bidnamubackend/auth/exception/UnknownTokenException.java
  src/main/java/com/bidnamu/bidnamubackend/auth/service/AuthService.java
  src/main/java/com/bidnamu/bidnamubackend/auth/service/UserDetailsServiceImpl.java
  src/main/java/com/bidnamu/bidnamubackend/auth/util/UserDetailsImpl.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/bidnamu/bidnamubackend/user/domain/User.java
  src/main/java/com/bidnamu/bidnamubackend/user/exception/UnknownUserException.java
  src/main/java/com/bidnamu/bidnamubackend/user/repository/UserRepository.java
  src/main/java/com/bidnamu/bidnamubackend/user/service/UserService.java
  src/main/resources/application-dev.yml
  src/test/java/com/bidnamu/bidnamubackend/auth/jwt/TokenProviderTest.java
  src/test/java/com/bidnamu/bidnamubackend/auth/jwt/service/AuthServiceTest.java
Labels: feature

#36 [#35] 토큰 필터 적용문제 해결
  src/main/java/com/bidnamu/bidnamubackend/auth/config/SecurityConfig.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/TokenAuthenticationFilter.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/TokenProvider.java
  src/main/java/com/bidnamu/bidnamubackend/auth/domain/Role.java
  src/main/java/com/bidnamu/bidnamubackend/auth/service/AuthService.java
  src/main/java/com/bidnamu/bidnamubackend/user/service/UserService.java
Labels: fix

#37 [#25] 경매 등록 기능 구현
  src/main/java/com/bidnamu/bidnamubackend/auction/controller/AuctionController.java
  src/main/java/com/bidnamu/bidnamubackend/auction/controller/CategoryController.java
  src/main/java/com/bidnamu/bidnamubackend/auction/domain/Auction.java
  src/main/java/com/bidnamu/bidnamubackend/auction/domain/AuctionImage.java
  src/main/java/com/bidnamu/bidnamubackend/auction/domain/AuctionStatus.java
  src/main/java/com/bidnamu/bidnamubackend/auction/domain/Category.java
  src/main/java/com/bidnamu/bidnamubackend/auction/dto/CreateAuctionDto.java
  src/main/java/com/bidnamu/bidnamubackend/auction/dto/request/CategoryFormDto.java
  src/main/java/com/bidnamu/bidnamubackend/auction/dto/request/CreateAuctionRequestDto.java
  src/main/java/com/bidnamu/bidnamubackend/auction/dto/response/AuctionDetailResponseDto.java
  src/main/java/com/bidnamu/bidnamubackend/auction/dto/response/CategoryResultDto.java
  src/main/java/com/bidnamu/bidnamubackend/auction/exception/InvalidCategoryDepthException.java
  src/main/java/com/bidnamu/bidnamubackend/auction/repository/AuctionRepository.java
  src/main/java/com/bidnamu/bidnamubackend/auction/repository/CategoryRepository.java
  src/main/java/com/bidnamu/bidnamubackend/auction/service/AuctionService.java
  src/main/java/com/bidnamu/bidnamubackend/auction/service/CategoryService.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/SecurityConfig.java
  src/main/java/com/bidnamu/bidnamubackend/file/domain/FileInfo.java
  src/main/java/com/bidnamu/bidnamubackend/file/service/FileService.java
  src/main/java/com/bidnamu/bidnamubackend/file/service/S3FileService.java
  src/main/java/com/bidnamu/bidnamubackend/global/domain/BaseFileInfoEntity.java
  src/main/java/com/bidnamu/bidnamubackend/global/util/FileNameUtils.java
  src/main/resources/application.yml
  src/test/java/com/bidnamu/bidnamubackend/auction/service/CreateAuctionTest.java
  src/test/java/com/bidnamu/bidnamubackend/category/service/CategoryCreationTest.java
  src/test/java/com/bidnamu/bidnamubackend/category/service/CategoryUpdateTest.java
  src/test/java/com/bidnamu/bidnamubackend/file/service/S3FileServiceTest.java
Labels: feature

#39 [#38] SecurityConfig 괄호로 인한 빌드에러 수정
  src/main/java/com/bidnamu/bidnamubackend/auth/config/SecurityConfig.java
Labels: bug, fix

#55 [#40] 회원 상태 변경 기능 구현
  src/main/java/com/bidnamu/bidnamubackend/auth/config/SecurityConfig.java
  src/main/java/com/bidnamu/bidnamubackend/user/controller/UserController.java
  src/main/java/com/bidnamu/bidnamubackend/user/domain/User.java
  src/main/java/com/bidnamu/bidnamubackend/user/dto/request/UserStatusUpdateRequestDto.java
  src/main/java/com/bidnamu/bidnamubackend/user/dto/response/UserStatusUpdateResponseDto.java
  src/main/java/com/bidnamu/bidnamubackend/user/service/UserService.java
  src/test/java/com/bidnamu/bidnamubackend/user/service/UserExpireTest.java
Labels: feature
