Repository BidNamu/bidnamu-backend, pull requests merged in 2023-11, with the labels that each got.

#3 [#2] DataSource 설정
  .gitignore
  docker-compose.yml
  src/main/java/com/bidnamu/bidnamubackend/global/config/DataSourceConfig.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/DataSourceType.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/RoutingDataSource.java
  src/main/resources/application-dev.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feature

#5 [#2] 기본 엔티티 틀 생성
  src/main/java/com/bidnamu/bidnamubackend/global/config/JpaConfig.java
  src/main/java/com/bidnamu/bidnamubackend/global/domain/BaseEntity.java
  src/main/java/com/bidnamu/bidnamubackend/global/domain/BaseTimeEntity.java
  src/main/resources/application-dev.yml
Labels: feature

#10 [#8] Redis Cache, Session 초기설정
  build.gradle
  docker-compose.yml
  src/main/java/com/bidnamu/bidnamubackend/global/config/RedisCacheConfig.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/RedisSessionConfig.java
  src/main/resources/application-dev.yml
Labels: feature

#12 [#8] 중복된 의존성 선언 제거
  build.gradle
Labels: fix

#16 [#14] Master, Slave 데이터베이스 연결 설정
  docker-compose.yml
  docker/master/Dockerfile
  docker/master/my.cnf
  docker/slave/Dockerfile
  docker/slave/my.cnf
  src/main/resources/application-dev.yml
Labels: feature

#17 [#11] DB Replication 테스트 구성
  build.gradle
  src/test/java/com/bidnamu/bidnamubackend/replication/config/DataSourceConfigTest.java
  src/test/java/com/bidnamu/bidnamubackend/replication/config/RoutingDataSourceConfigTest.java
  src/test/java/com/bidnamu/bidnamubackend/replication/service/ReplicationServiceTest.java
  src/test/java/com/bidnamu/bidnamubackend/testClass/TestEntity.java
  src/test/java/com/bidnamu/bidnamubackend/testClass/TestEntityRepository.java
  src/test/java/com/bidnamu/bidnamubackend/testClass/TestService.java
Labels: feature

#13 [#4] passwordEncoder 적용, 회원가입 구현
  build.gradle
  src/main/java/com/bidnamu/bidnamubackend/auth/common/CorsFilterConfig.java
  src/main/java/com/bidnamu/bidnamubackend/auth/common/SecurityConfig.java
  src/main/java/com/bidnamu/bidnamubackend/auth/domain/Authority.java
  src/main/java/com/bidnamu/bidnamubackend/auth/domain/Role.java
  src/main/java/com/bidnamu/bidnamubackend/global/domain/BaseTimeEntity.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/error_code/CommonErrorCode.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/error_code/ErrorCode.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/response/ErrorResponse.java
  src/main/java/com/bidnamu/bidnamubackend/global/util/HttpStatusResponseEntity.java
  src/main/java/com/bidnamu/bidnamubackend/user/controller/UserController.java
  src/main/java/com/bidnamu/bidnamubackend/user/domain/User.java
  src/main/java/com/bidnamu/bidnamubackend/user/dto/RegistrationRequestDto.java
  src/main/java/com/bidnamu/bidnamubackend/user/dto/RegistrationResponseDto.java
  src/main/java/com/bidnamu/bidnamubackend/user/exception/DuplicatedEmailException.java
  src/main/java/com/bidnamu/bidnamubackend/user/repository/UserRepository.java
  src/main/java/com/bidnamu/bidnamubackend/user/service/UserService.java
  src/test/java/com/bidnamu/bidnamubackend/user/domain/UserTest.java
  src/test/java/com/bidnamu/bidnamubackend/user/service/UserRegistrationTest.java
Labels: feature

#18 [#4] 회원가입 시 닉네임 중복 검증 구현
  src/main/java/com/bidnamu/bidnamubackend/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/bidnamu/bidnamubackend/user/controller/UserController.java
  src/main/java/com/bidnamu/bidnamubackend/user/exception/DuplicatedNicknameException.java
  src/main/java/com/bidnamu/bidnamubackend/user/repository/UserRepository.java
  src/main/java/com/bidnamu/bidnamubackend/user/service/UserService.java
  src/test/java/com/bidnamu/bidnamubackend/user/service/UserRegistrationTest.java
Labels: feature

#22 [#19] URI 접두사 지정
  src/main/resources/application.yml
Labels: chore

#23 develop -> main
  .gitignore
  build.gradle
  docker-compose.yml
  docker/master/Dockerfile
  docker/master/my.cnf
  docker/slave/Dockerfile
  docker/slave/my.cnf
  src/main/java/com/bidnamu/bidnamubackend/auth/config/CorsFilterConfig.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/SecurityConfig.java
  src/main/java/com/bidnamu/bidnamubackend/auth/domain/Authority.java
  src/main/java/com/bidnamu/bidnamubackend/auth/domain/Role.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/DataSourceConfig.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/DataSourceType.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/JpaConfig.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/RedisCacheConfig.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/RedisSessionConfig.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/RoutingDataSource.java
  src/main/java/com/bidnamu/bidnamubackend/global/domain/BaseEntity.java
  src/main/java/com/bidnamu/bidnamubackend/global/domain/BaseTimeEntity.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/error_code/CommonErrorCode.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/error_code/ErrorCode.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/response/ErrorResponse.java
  src/main/java/com/bidnamu/bidnamubackend/global/util/HttpStatusResponseEntity.java
  src/main/java/com/bidnamu/bidnamubackend/user/controller/UserController.java
  src/main/java/com/bidnamu/bidnamubackend/user/domain/User.java
  src/main/java/com/bidnamu/bidnamubackend/user/dto/RegistrationRequestDto.java
  src/main/java/com/bidnamu/bidnamubackend/user/dto/RegistrationResponseDto.java
  src/main/java/com/bidnamu/bidnamubackend/user/exception/DuplicatedEmailException.java
  src/main/java/com/bidnamu/bidnamubackend/user/exception/DuplicatedNicknameException.java
  src/main/java/com/bidnamu/bidnamubackend/user/repository/UserRepository.java
  src/main/java/com/bidnamu/bidnamubackend/user/service/UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/bidnamu/bidnamubackend/replication/config/DataSourceConfigTest.java
  src/test/java/com/bidnamu/bidnamubackend/replication/config/RoutingDataSourceConfigTest.java
  src/test/java/com/bidnamu/bidnamubackend/replication/service/ReplicationServiceTest.java
  src/test/java/com/bidnamu/bidnamubackend/testClass/TestEntity.java
  src/test/java/com/bidnamu/bidnamubackend/testClass/TestEntityRepository.java
  src/test/java/com/bidnamu/bidnamubackend/testClass/TestService.java
  src/test/java/com/bidnamu/bidnamubackend/user/domain/UserTest.java
  src/test/java/com/bidnamu/bidnamubackend/user/service/UserRegistrationTest.java
Labels: approve

#24 [#20] Swagger 설정 추가
  build.gradle
Labels: feature

#27 [#26] 카테고리 관련 기능 구현
  src/main/java/com/bidnamu/bidnamubackend/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/bidnamu/bidnamubackend/global/util/HttpStatusResponseEntity.java
  src/main/java/com/bidnamu/bidnamubackend/item/controller/CategoryController.java
  src/main/java/com/bidnamu/bidnamubackend/item/domain/Category.java
  src/main/java/com/bidnamu/bidnamubackend/item/dto/request/CategoryFormDto.java
  src/main/java/com/bidnamu/bidnamubackend/item/dto/response/CategoryResultDto.java
  src/main/java/com/bidnamu/bidnamubackend/item/repository/CategoryRepository.java
  src/main/java/com/bidnamu/bidnamubackend/item/service/CategoryService.java
  src/test/java/com/bidnamu/bidnamubackend/category/service/CategoryCreationTest.java
  src/test/java/com/bidnamu/bidnamubackend/category/service/CategoryUpdateTest.java
Labels: feature

#31 [#26] 카테고리 depth 제한 추가
  src/main/java/com/bidnamu/bidnamubackend/item/domain/Category.java
Labels: fix

#30 [#28] AWS S3 연결 및 파일업로드 설정
  build.gradle
  src/main/java/com/bidnamu/bidnamubackend/global/config/S3Config.java
  src/main/java/com/bidnamu/bidnamubackend/global/domain/BaseFileInfoEntity.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/error_code/CommonErrorCode.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/bidnamu/bidnamubackend/global/service/FileService.java
  src/main/java/com/bidnamu/bidnamubackend/global/service/S3FileService.java
  src/main/java/com/bidnamu/bidnamubackend/global/util/FileNameUtils.java
  src/main/resources/application.yml
Labels: feature
