Repository BidNamu/bidnamu-backend, pull requests merged in 2024-01, with the labels that each got.

#57 [#56] final 키워드 설정, dto 패키지 분리
  src/main/java/com/bidnamu/bidnamubackend/auction/dto/response/CategoryResultDto.java
  src/main/java/com/bidnamu/bidnamubackend/auction/exception/InvalidCategoryDepthException.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/CorsFilterConfig.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/JwtAccessDeniedHandler.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/TokenAuthenticationFilter.java
  src/main/java/com/bidnamu/bidnamubackend/auth/exception/UnknownTokenException.java
  src/main/java/com/bidnamu/bidnamubackend/file/exception/FileUploadException.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/DataSourceConfig.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/RedisCacheConfig.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/RedisSessionConfig.java
  src/main/java/com/bidnamu/bidnamubackend/global/domain/BaseEntity.java
  src/main/java/com/bidnamu/bidnamubackend/user/controller/UserController.java
  src/main/java/com/bidnamu/bidnamubackend/user/domain/User.java
  src/main/java/com/bidnamu/bidnamubackend/user/dto/request/RegistrationRequestDto.java
  src/main/java/com/bidnamu/bidnamubackend/user/dto/response/RegistrationResponseDto.java
  src/main/java/com/bidnamu/bidnamubackend/user/exception/DuplicatedEmailException.java
  src/main/java/com/bidnamu/bidnamubackend/user/exception/DuplicatedNicknameException.java
  src/main/java/com/bidnamu/bidnamubackend/user/exception/UnknownUserException.java
  src/main/java/com/bidnamu/bidnamubackend/user/repository/UserRepository.java
  src/main/java/com/bidnamu/bidnamubackend/user/service/UserService.java
  src/test/java/com/bidnamu/bidnamubackend/auth/jwt/TokenProviderTest.java
  src/test/java/com/bidnamu/bidnamubackend/auth/jwt/service/AuthServiceTest.java
  src/test/java/com/bidnamu/bidnamubackend/replication/config/DataSourceConfigTest.java
  src/test/java/com/bidnamu/bidnamubackend/replication/config/RoutingDataSourceConfigTest.java
  src/test/java/com/bidnamu/bidnamubackend/replication/service/ReplicationServiceTest.java
  src/test/java/com/bidnamu/bidnamubackend/user/domain/UserTest.java
  src/test/java/com/bidnamu/bidnamubackend/user/service/UserRegistrationTest.java
Labels: refactor

#59 [#53] 토큰 검증 실패 시 예외처리가 되지 않는 문제 해결
  src/main/java/com/bidnamu/bidnamubackend/auth/config/AccessDeniedHandlerImpl.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/SecurityConfig.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/TokenAuthenticationFilter.java
  src/main/java/com/bidnamu/bidnamubackend/auth/exception/JwtErrorCode.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/response/ErrorResponse.java
Labels: fix

#60 [#34] redis blacklist 설정을 통한 로그아웃 기능 구현
  build.gradle
  src/main/java/com/bidnamu/bidnamubackend/auth/config/SecurityConfig.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/TokenAuthenticationFilter.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/TokenProvider.java
  src/main/java/com/bidnamu/bidnamubackend/auth/controller/AuthController.java
  src/main/java/com/bidnamu/bidnamubackend/auth/domain/RefreshToken.java
  src/main/java/com/bidnamu/bidnamubackend/auth/dto/response/LogoutResponseDto.java
  src/main/java/com/bidnamu/bidnamubackend/auth/repository/RefreshTokenRedisRepository.java
  src/main/java/com/bidnamu/bidnamubackend/auth/service/AuthService.java
  src/main/java/com/bidnamu/bidnamubackend/global/config/RedisSessionConfig.java
  src/main/java/com/bidnamu/bidnamubackend/user/domain/User.java
  src/main/java/com/bidnamu/bidnamubackend/user/repository/UserRepository.java
  src/main/java/com/bidnamu/bidnamubackend/user/service/UserService.java
  src/main/resources/application-dev.yml
  src/test/java/com/bidnamu/bidnamubackend/auth/jwt/service/AuthServiceTest.java
Labels: feature

#65 [#64] feature/34 -> develop PR 도중 생긴 오류 해결 및 500 에러 뜨던 부분 수정
  src/main/java/com/bidnamu/bidnamubackend/auth/config/TokenAuthenticationFilter.java
  src/main/java/com/bidnamu/bidnamubackend/auth/config/TokenProvider.java
  src/main/java/com/bidnamu/bidnamubackend/auth/exception/JwtErrorCode.java
  src/main/java/com/bidnamu/bidnamubackend/auth/repository/RefreshTokenRedisRepository.java
  src/main/java/com/bidnamu/bidnamubackend/auth/service/AuthService.java
  src/main/java/com/bidnamu/bidnamubackend/global/exception/handler/GlobalExceptionHandler.java
Labels: fix
